version: "3.5"

volumes:
  postgres:
  pgadmin:
  minio:

services:
  ferdig:
    image: jappyjan/ferdig:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8083
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env

  postgres:
    image: postgres:latest
    restart: always
    stdin_open: false
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ferdig
    volumes:
      - postgres:/var/lib/postgresql/data
    hostname: postgres

  minio:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z
    command: "server --console-address \":9001\" /minio/data"
    stdin_open: false
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    volumes:
      - minio:/data
