version: '3.3'

volumes:
  postgres:
  pgadmin:
  mongo:

services:
  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres

  mongo:
    extends:
      service: mongo
      file: ./docker-compose.yml

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8081:80
