version: "3.5"

volumes:
  postgres:
  pgadmin:
  mongo:

services:
  ferdig:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: ferdig/server:latest
    restart: always
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: agenda
    volumes:
      - mongo:/data/db
