version: "3.5"

volumes:
  postgres:
  pgadmin:
  mongo:
  minio:

services:
  ferdig:
    image: jappyjan/ferdig
    restart: always
    expose:
      - 8081
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: agenda
    volumes:
      - mongo:/data/db

  minio:
    image: minio/minio:RELEASE.2021-07-30T00-02-00Z
    command: "server --console-address \":9001\" /minio/data"
    expose:
      - 9000
      - 9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    hostname: minio
    volumes:
      - minio:/data
