version: '3.5'

volumes:
  postgres:
  pgadmin:
  mongo:
  minio:

services:
  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres

  mongo:
    extends:
      service: mongo
      file: ./docker-compose.yml

  minio:
    extends:
      service: minio
      file: ./docker-compose.yml

  mail:
    image: jeanberu/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
