version: '3.5'

volumes:
  postgres:
  pgadmin:
  mongo:
  minio:

services:
  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres
    ports:
    - 5432:5432

  mongo:
    extends:
      service: mongo
      file: ./docker-compose.yml
    ports:
      - 27017:27017

  minio:
    extends:
      service: minio
      file: ./docker-compose.yml
    ports:
      - 9000:9000
      - 9001:9001

  mail:
    image: jeanberu/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
